#!/usr/bin/env tsx
import { writeFileSync } from "fs";
import { join } from "path";
import { db, schema } from "../db";
import { eq, sql } from "drizzle-orm";
import {
  MAX_DOCUMENT_SLUG_LENGTH,
  canonicalDocumentKey,
  finalizeDocumentSlug,
  isStaticBuildableSlug,
  normalizeAlias,
} from "../lib/lovdata/slug";

async function migrateLongSlugs() {
  const documents = await db
    .select()
    .from(schema.legalDocuments)
    .where(sql`char_length(${schema.legalDocuments.slug}) > ${MAX_DOCUMENT_SLUG_LENGTH}`);

  if (documents.length === 0) {
    console.log("No slugs exceed max length.");
    writeRedirects({});
    return;
  }

  console.log(`Shortening ${documents.length} overlong slugs...`);

  const reservedSlugs = new Set(
    (
      await db
        .select({ slug: schema.legalDocuments.slug })
        .from(schema.legalDocuments)
    )
      .map((d) => d.slug)
      .filter((slug) => isStaticBuildableSlug(slug))
  );

  const redirects: Record<string, string> = {};

  for (const doc of documents) {
    reservedSlugs.delete(doc.slug);
    let newSlug = finalizeDocumentSlug(
      doc.slug,
      canonicalDocumentKey(doc.documentKey)
    );

    if (reservedSlugs.has(newSlug)) {
      newSlug = finalizeDocumentSlug(
        `${doc.slug}-${canonicalDocumentKey(doc.documentKey).replace(/\//g, "-")}`,
        canonicalDocumentKey(doc.documentKey)
      );
    }

    reservedSlugs.add(newSlug);
    redirects[doc.slug] = newSlug;

    await db
      .update(schema.legalDocuments)
      .set({ slug: newSlug })
      .where(eq(schema.legalDocuments.id, doc.id));

    await db
      .insert(schema.documentAliases)
      .values({
        documentId: doc.id,
        alias: doc.slug,
        normalizedAlias: normalizeAlias(doc.slug),
        source: "manual",
      })
      .onConflictDoNothing();

    console.log(`  ${doc.slug.slice(0, 60)}… -> ${newSlug}`);
  }

  writeRedirects(redirects);
  console.log(`Wrote ${Object.keys(redirects).length} slug redirects.`);
}

function writeRedirects(redirects: Record<string, string>) {
  const path = join(process.cwd(), "lib/slug-redirects.ts");
  const body = Object.entries(redirects)
    .map(([from, to]) => `  ${JSON.stringify(from)}: ${JSON.stringify(to)},`)
    .join("\n");

  writeFileSync(
    path,
    `/** Old slug -> new slug. Generated by scripts/migrate-long-slugs.ts */\nexport const documentSlugRedirects: Record<string, string> = {\n${body}\n};\n`
  );
}

migrateLongSlugs()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
